os: linux
language: node_js
node_js:
    - 12.18.3
cache:
    directories:
        - node_modules
before_install:
    - npm update --silent
install:
    - npm install --silent
    - npm install -g codecov
script:
    - npm test
    - codecov --token=$CODECOV_TOKEN
deploy:
    provider: heroku
    api_key:
        security: $HEROKU_API_KEY
    app: mockable-api
    on: task/heroku-deploy
