os: linux
language: node_js
cache:
    directories:
        - node_modules
before_install:
    - npm update
install:
    - npm install --silent
    - npm install -g codecov
script:
    - npm test
    - codecov
