version: "3"

services:
    api:
        container_name: mockable-api
        restart: always
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run debug
        environment:
            - NODE_ENV=development
        ports:
            - "3000:3000"
            - "9200:9200"
        volumes:
            - ./:/usr/src/app
        depends_on:
            - db
        networks:
            - mockable
            - mockable-cache
    db:
        container_name: mockable-db
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - "27017:27017"
        volumes:
            - mockable-data:/data
        networks:
            - mockable
    cache:
        container_name: mockable-cache
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - mockable-cache

networks:
    mockable:
        driver: bridge
    mockable-cache:
        driver: bridge

volumes:
    mockable-data:
